/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject545;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author EKUStudent
 */
public class AddMealPlanGUI extends javax.swing.JPanel {

    /**
     * Creates new form AddMealPlanGUI
     */
    // mealPlan is an instance of the MealDays class that will allow us to use the methods contained in that class
    public MealDays mealPlan = null;

    // mealDays will hold all the mealDays that need inserted into the database 
    public List<MealDays> mealDays = new ArrayList<MealDays>();

    public PreparedStatement pst = null;
    public Connection conn = null;
    public OracleResultSet rs = null;

    // EDIT_MODE: determines if we are editing an old meal plan or creating a new meal plan
    public final boolean EDIT_MODE;

    public AddMealPlanGUI(String mealPlanTitle, JFrame frame) {
        initComponents();

        // Maximize the size of the jframe.
        //frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.add(this);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        // Below is custom close operation.
        WindowListener exitListener = new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                // Show the meal plans form.
                JFrame frame = new JFrame("Meal Plans");

                MealPlanGUI mealPlanGUI = new MealPlanGUI(frame);
            }
        };
        frame.addWindowListener(exitListener);  // Add the custom designed listener.

        if (mealPlanTitle != null) {  // We are editing an old plan.
            mealPlan = new MealDays(mealPlanTitle);
            EDIT_MODE = true;
            submitButton.setText("Submit Changes");
        } else {  // Creating a new plan.
            EDIT_MODE = false;
            submitButton.setText("Submit Meal Plan");
        }

        // NOthing selected by default - so hide modify and delete buttons.
        deleteButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        daysOfWeekComboBox = new javax.swing.JComboBox<>();
        mealNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mealTitlesComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mealPlanTitleTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        addMealButton = new javax.swing.JButton();

        submitButton.setText("Submit Meal Plan");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        daysOfWeekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));

        mealNameTextField.setText("Breakfast, brunch, lunch, etc.");

        jLabel1.setText("Served during:");

        mealTitlesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mealsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mealsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mealsList);

        jLabel2.setText("Meal:");

        jLabel3.setText("My Meals in this Plan");

        deleteButton.setText("Delete");

        jLabel4.setText("Meal Plan Title:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addMealButton.setText("Add Meal");
        addMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mealTitlesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mealPlanTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(daysOfWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(mealNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addMealButton)
                        .addGap(238, 238, 238)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mealPlanTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(daysOfWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mealTitlesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(addMealButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getMeals() {
        if (EDIT_MODE) { // get all meals used in this meal plan (if in edit mode) for the selected day of the week

        } else { // get all meals in the database (if creating a new meal plan)

        }
    }

    private void mealsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mealsListValueChanged
        // Hide modify button if only item is selected.
        if (mealsList.getSelectedIndices().length >= 1) {  // Allow deletion of one or more meals.
            deleteButton.setVisible(true);
        } else {  // Zero items selected - can't delete nothing!
            deleteButton.setVisible(false);
        }
    }//GEN-LAST:event_mealsListValueChanged

    private boolean stringNotEmpty(String mealPlanName) {
        if (mealPlanName.equals("") || mealPlanName == null) {
            return false;
        }
        return true;
    }

    private boolean mealPlanNameDoesNotExist(String mealPlanTitle) {
        conn = ConnectDb.setupConnection();
        try {
            String sqlStatement = "select * from MEALPLANS where title = '" + mealPlanTitle + "'";
            pst = (OraclePreparedStatement) conn.prepareStatement(sqlStatement);
            rs = (OracleResultSet) pst.executeQuery();
            if (rs.next()) {
                return false;
            } else {
                return true;
            }

        } catch (Exception ex) {
            System.out.println(ex);
        } finally {
            ConnectDb.close(rs);
            ConnectDb.close(pst);
            ConnectDb.close(conn);
        }
        System.out.println("There was a problem checking if the meal plan title exists or not.");
        return false;
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed

        //  Go back to the meal plan screen without submitting changes to the database.
        JFrame frame = new JFrame("My Meal Plans");

        MealPlanGUI mealPlanGUI = new MealPlanGUI(frame);

        // Close the frame, don't submit changes.
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealButtonActionPerformed
        // make sure the meal name is not empty
        if (stringNotEmpty(mealNameTextField.getText())) {
            // now make sure that this specific meal title, with this specific meal name, on this specific day does not already exist in the list
            String mealTitle = mealTitlesComboBox.getSelectedItem().toString();
            String mealName = mealNameTextField.getText();
            String dayOfWeek = daysOfWeekComboBox.getSelectedItem().toString();
            MealDays md = new MealDays(mealTitle, mealName, dayOfWeek);
            if (!mealDayDoesNotExist(md)) {
                mealDays.add(md);  // append to the list
                System.out.println("meal day does not exist");
            } else {
                JOptionPane.showMessageDialog(this,
                        "That meal day for this meal plan already has a scheduled meal!",
                        "Ingredient Not Added",
                        JOptionPane.ERROR_MESSAGE);
                System.out.println("meal day exists");
            }
        }
    }//GEN-LAST:event_addMealButtonActionPerformed

    private boolean mealDayDoesNotExist(MealDays md) {
        for (MealDays mealDay : mealDays) {
            if (mealDay.getDayOfWeek().equals(md.getDayOfWeek()) && mealDay.getMealName().equals(md.getMealName())) {
                // this meal already exists in the list
                return true;
            }
        }
        // passed all the checks - meal does not exist
        return false;
    }


    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (mealPlanNameDoesNotExist(mealPlanTitleTextField.getText()) && stringNotEmpty(mealPlanTitleTextField.getText())) {
            // insert the meal plan into the database

        }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMealButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> daysOfWeekComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mealNameTextField;
    private javax.swing.JTextField mealPlanTitleTextField;
    private javax.swing.JComboBox<String> mealTitlesComboBox;
    private javax.swing.JList<String> mealsList;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
