/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject545;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ethan_2
 */
public class WelcomeScreenGUI extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeScreenGUI
     */
    public WelcomeScreenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingredientsButton = new javax.swing.JButton();
        recipesButton = new javax.swing.JButton();
        mealsButton = new javax.swing.JButton();
        mealPlansButton = new javax.swing.JButton();

        ingredientsButton.setText("Ingredients");
        ingredientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientsButtonActionPerformed(evt);
            }
        });

        recipesButton.setText("Recipes");

        mealsButton.setText("Meals");

        mealPlansButton.setText("Meal Plans");
        mealPlansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealPlansButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingredientsButton)
                .addGap(18, 18, 18)
                .addComponent(mealsButton)
                .addGap(18, 18, 18)
                .addComponent(mealPlansButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipesButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingredientsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recipesButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mealsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mealPlansButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mealPlansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealPlansButtonActionPerformed

        // Show the meal plans form.
        JFrame frame = new JFrame("My Meal Planner");

        MealPlanGUI mealPlans = new MealPlanGUI(frame);
        
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();  // Close the welcome menu.
    }//GEN-LAST:event_mealPlansButtonActionPerformed

    private void ingredientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientsButtonActionPerformed

        // Show the meal plans form.
        JFrame frame = new JFrame("My Ingredients");

        // Show the ingredients form.
        IngredientsGUI ingredientsScreen = new IngredientsGUI(frame);

        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();  // Close the welcome menu.
    }//GEN-LAST:event_ingredientsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingredientsButton;
    private javax.swing.JButton mealPlansButton;
    private javax.swing.JButton mealsButton;
    private javax.swing.JButton recipesButton;
    // End of variables declaration//GEN-END:variables
}
